name="name"
description="description"

countryName="countryName"
countryShortName="countryShortName"
countryTwoChar="countryTwoChar"
countryThreeChar="countryThreeChar"

usersLoginID="usersLoginID"
usersFirstName="usersFirstName"
usersLastName="usersLastName"
usersInitial="usersInitial"
usersAddressOne="usersAddressOne"
usersAddressTwo="usersAddressTwo"
usersAddressThree="usersAddressThree"
usersDivision="usersDivision"
usersDesignation="usersDesignation"
usersQualification="usersQualification"
usersBloodGroup="usersBloodGroup"
usersJobDescription="usersJobDescription"
usersEmail="usersEmail"
usersPhoneNumber="9876543210"
usersMobileNumber="9999999999"
usersCountry="country"
usersSite="site"
usersUserRole="userRole"
usersIsActive="usersIsActive"
usersIsUnLock="usersIsUnLock"

licenseAuthorityName="licenseAuthorityName"
licenseAuthorityShortName="licenseAuthorityShortName"
licenseAuthorityCountry="licenseAuthorityCountry"
licenseAuthorityCountryShortName="licenseAuthorityCountryShortName"

chargeBandName="chargeBandName"
chargeBandDescription="chargeBandDescription"
chargeBandPrice="chargeBandPrice"